module.exports = {
  getBook: require("./getBook.controller"),
  getAllBooks: require("./getAllBooks.controller"),
  createBook: require("./createBook.controller"),
  editBook: require("./editBook.controller"),
  deleteBook: require("./deleteBook.controller"),
  borrowBook: require("./borrowBook.controller"),
  returnBook: require("./returnBook.controller"),
  bookCategory: require("./bookCategory"),
  getAllBorrowedBooks: require("./getAllBorrowedBooks.controller"),
  getAllDefaultedBooks: require("./getAllDefaultedBooks.controller"),
  getUserBorrowedBooks: require("./getUserBorrowedBooks.controller"),
  getUserDefaultedBooks: require("./getUserDefaultedBooks.controller"),
  getAllCurrentlyBorrowedBooks: require("./getAllCurrentlyBorrowedBooks.controller"),
  getAllCurrentlyDefaultedBooks: require("./getAllCurrentlyDefaultedBooks.controller"),
  getUserCurrentlyBorrowedBooks: require("./getUserCurrentlyBorrowedBooks.controller"),
  getUserCurrentlyDefaultedBooks: require("./getUserCurrentlyDefaultedBooks.controller"),
};
